# Generated by Django 5.2.4 on 2025-07-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('expiry_date', models.DateField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
